apiVersion: v1
kind: Service
metadata:
  name: gitops-cdk8s-argocd-service-c835934b
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: website
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
data:
  index.html: <html><h1>Version 1</h1></html
metadata:
  name: gitops-cdk8s-argocd-index.html-c824e138
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-cdk8s-argocd-deployment-c881a545
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: nginx:1.23.2
          name: webserver
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: nginx-index-file
      volumes:
        - configMap:
            name: gitops-cdk8s-argocd-index.html-c824e138
          name: nginx-index-file
